# Generated by Django 4.2.13 on 2024-07-28 03:26

import apps.profiles.models
import autoslug.fields
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("pkid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.profiles.models.avatar_upload_to,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("mason", "Mason"),
                            ("carpenter", "Carpenter"),
                            ("plumber", "Plumber"),
                            ("roofer", "Roofer"),
                            ("painter", "Painter"),
                            ("electrician", "Electrician"),
                            ("hvac", "HVAC"),
                            ("tenant", "Tenant"),
                        ],
                        default="tenant",
                        max_length=20,
                        verbose_name="Occupation",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+91-9204178296",
                        max_length=15,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "country_of_origin",
                    django_countries.fields.CountryField(
                        default="IN", max_length=2, verbose_name="Country of Origin"
                    ),
                ),
                (
                    "city_of_origin",
                    models.CharField(
                        default="Nagpur", max_length=180, verbose_name="City of Origin"
                    ),
                ),
                (
                    "report_count",
                    models.PositiveIntegerField(default=0, verbose_name="Report Count"),
                ),
                (
                    "reputation",
                    models.PositiveIntegerField(default=100, verbose_name="Reputation"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from=apps.profiles.models.get_user_username,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
