# Generated by Django 4.2.13 on 2024-07-08 01:45

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.profiles.models.avatar_upload_to,
                verbose_name="Avatar",
            ),
        ),
    ]
