# Generated by Django 4.2.13 on 2024-07-08 05:08

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.profiles.models.avatar_upload_to,
                verbose_name="Avatar",
            ),
        ),
    ]
