#!/usr/bin/env bash


# Set bash to exit immediately if a command fails
set -o errexit
# Return a non-zero exit status if any part of a pipeline fails
set -o pipefail
# Treat unset variables as an error when expanding them
set -o nounset


# Get the directory of the script
working_dir="$(dirname ${0})"


# Source the constants and messages scripts
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


# Display a welcome message
message_welcome "These are the backups you have got:"


# List the files in the backup directory with human-readable sizes and sort by modification time
ls -lht "${BACKUP_DIR_PATH}"
