# Generated by Django 4.2.13 on 2024-07-28 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="posts.post",
                verbose_name="Post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="bookmarked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bookmarked by",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="downvoted_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvoted_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Downvoted by",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="upvoted_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Upvoted by",
            ),
        ),
    ]
