#!/bin/bash


# Set bash to exit immediately if a command fails
set -o errexit
# Set bash to treat unset variables as an error when expanding them
set -o nounset


# Execute watchfiles to monitor Python files and start Celery worker with specified logging level
exec watchfiles --filter python celery.__main__.main --args '-A config.celery_app worker -l INFO'
